2015-10-20 09:23:32.398 5114 INFO neutron.common.config [-] Logging enabled!
2015-10-20 09:23:32.403 5114 INFO neutron.common.config [-] /usr/bin/neutron-dhcp-agent version 2014.2.3-19.el7ost
2015-10-20 09:23:32.574 5114 INFO oslo.messaging._drivers.impl_rabbit [req-cfe86490-7de8-44de-82bd-984feb22e67a ] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 09:23:32.671 5114 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 09:23:32.811 5114 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 09:23:32.815 5114 INFO oslo.messaging._drivers.impl_rabbit [req-cfe86490-7de8-44de-82bd-984feb22e67a ] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 09:23:32.856 5114 INFO oslo.messaging._drivers.impl_rabbit [req-cfe86490-7de8-44de-82bd-984feb22e67a ] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 09:23:32.971 5114 INFO neutron.agent.dhcp_agent [-] DHCP agent started
2015-10-20 09:23:32.987 5114 INFO oslo.messaging._drivers.impl_rabbit [req-cfe86490-7de8-44de-82bd-984feb22e67a ] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 09:24:33.011 5114 ERROR neutron.agent.dhcp_agent [req-cfe86490-7de8-44de-82bd-984feb22e67a None] Failed reporting state!
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent Traceback (most recent call last):
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp_agent.py", line 595, in _report_state
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     self.state_rpc.report_state(ctx, self.agent_state, self.use_call)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/neutron/agent/rpc.py", line 72, in report_state
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     return self.call(context, msg)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/neutron/common/log.py", line 34, in wrapper
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     return method(*args, **kwargs)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/neutron/common/rpc.py", line 161, in call
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     context, msg, rpc_method='call', **kwargs)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/neutron/common/rpc.py", line 187, in __call_rpc_method
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     return func(context, msg['method'], **msg['args'])
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/rpc/client.py", line 389, in call
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     return self.prepare().call(ctxt, method, **kwargs)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/rpc/client.py", line 152, in call
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     retry=self.retry)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/transport.py", line 90, in _send
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     timeout=timeout, retry=retry)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 416, in send
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     retry=retry)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 405, in _send
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     result = self._waiter.wait(msg_id, timeout)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 293, in wait
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     reply, ending = self._poll_connection(msg_id, timer)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 240, in _poll_connection
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     self._raise_timeout_exception(msg_id)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 209, in _raise_timeout_exception
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent     _('Timed out waiting for a reply to message ID %s.') % msg_id)
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent MessagingTimeout: Timed out waiting for a reply to message ID 2a2a9edca7544ff492417a1b9143f966.
2015-10-20 09:24:33.011 5114 TRACE neutron.agent.dhcp_agent 
2015-10-20 09:24:33.024 5114 WARNING neutron.openstack.common.loopingcall [-] task run outlasted interval by 30.454294 sec
2015-10-20 09:24:33.111 5114 INFO neutron.agent.dhcp_agent [req-fd77bb0e-812c-4b7d-9f9a-277bed7e7e49 None] Synchronizing state
2015-10-20 09:24:33.409 5114 INFO neutron.agent.dhcp_agent [req-fd77bb0e-812c-4b7d-9f9a-277bed7e7e49 None] Synchronizing state complete
2015-10-20 10:17:03.114 5114 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to consume message from queue: [Errno 110] Connection timed out
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 674, in ensure
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 762, in _consume
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit     return self.connection.drain_events(timeout=poll_timeout)
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit     return self.transport.drain_events(self.connection, **kwargs)
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 91, in drain_events
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit     return connection.drain_events(**kwargs)
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 302, in drain_events
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit     chanmap, None, timeout=timeout,
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 365, in _wait_multiple
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit     channel, method_sig, args, content = read_timeout(timeout)
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 336, in read_timeout
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit     return self.method_reader.read_method()
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit     raise m
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit error: [Errno 110] Connection timed out
2015-10-20 10:17:03.114 5114 TRACE oslo.messaging._drivers.impl_rabbit 
2015-10-20 10:17:03.123 5114 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2015-10-20 10:17:04.125 5114 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 10:17:04.186 5114 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 10.12.27.29:5672 is unreachable: [Errno 101] ENETUNREACH. Trying again in 1 seconds.
2015-10-20 10:17:05.188 5114 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2015-10-20 10:17:06.198 5114 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 10:17:06.304 5114 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 10.12.27.29:5672 is unreachable: [Errno 101] ENETUNREACH. Trying again in 3 seconds.
2015-10-20 10:17:09.307 5114 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2015-10-20 10:17:10.309 5114 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 10:17:10.345 5114 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 10.12.27.29:5672 is unreachable: [Errno 101] ENETUNREACH. Trying again in 5 seconds.
2015-10-20 10:17:15.350 5114 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2015-10-20 10:17:15.861 5114 ERROR oslo.messaging._drivers.impl_rabbit [req-01c48969-2a67-4d1d-9a0c-ad215d2f58a5 ] Failed to publish message to topic 'q-plugin': Socket closed
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 674, in ensure
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 782, in _publish
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     publisher = cls(self.conf, self.channel, topic=topic, **kwargs)
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 393, in __init__
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     **options)
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 339, in __init__
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     self.reconnect(channel)
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 347, in reconnect
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     routing_key=self.routing_key)
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/messaging.py", line 85, in __init__
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     self.revive(self._channel)
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/messaging.py", line 218, in revive
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     self.declare()
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/messaging.py", line 105, in declare
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     self.exchange.declare()
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/entity.py", line 166, in declare
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     nowait=nowait, passive=passive,
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/channel.py", line 620, in exchange_declare
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     (40, 11),  # Channel.exchange_declare_ok
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/abstract_channel.py", line 67, in wait
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     self.channel_id, allowed_methods)
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 240, in _wait_method
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     self.method_reader.read_method()
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit     raise m
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit IOError: Socket closed
2015-10-20 10:17:15.861 5114 TRACE oslo.messaging._drivers.impl_rabbit 
2015-10-20 10:17:15.870 5114 INFO oslo.messaging._drivers.impl_rabbit [req-01c48969-2a67-4d1d-9a0c-ad215d2f58a5 ] Delaying reconnect for 1.0 seconds...
2015-10-20 10:17:16.352 5114 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 10:17:16.439 5114 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 10:17:16.897 5114 INFO oslo.messaging._drivers.impl_rabbit [req-01c48969-2a67-4d1d-9a0c-ad215d2f58a5 ] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 10:17:17.000 5114 INFO oslo.messaging._drivers.impl_rabbit [req-01c48969-2a67-4d1d-9a0c-ad215d2f58a5 ] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 12:20:20.541 5114 INFO neutron.openstack.common.service [req-b415246f-7a97-4a77-b0fb-92608fb3eb8e None] Caught SIGTERM, exiting
2015-10-20 12:41:30.031 4436 INFO neutron.common.config [-] Logging enabled!
2015-10-20 12:41:30.079 4436 INFO neutron.common.config [-] /usr/bin/neutron-dhcp-agent version 2014.2.3-19.el7ost
2015-10-20 12:41:30.395 4436 INFO oslo.messaging._drivers.impl_rabbit [req-3c1c9ec1-9e07-4287-ac23-7a1b61fdd0be ] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 12:41:30.579 4436 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 12:41:30.794 4436 INFO oslo.messaging._drivers.impl_rabbit [req-3c1c9ec1-9e07-4287-ac23-7a1b61fdd0be ] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 12:41:30.798 4436 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 12:41:30.849 4436 INFO oslo.messaging._drivers.impl_rabbit [req-3c1c9ec1-9e07-4287-ac23-7a1b61fdd0be ] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 12:41:31.045 4436 INFO oslo.messaging._drivers.impl_rabbit [req-3c1c9ec1-9e07-4287-ac23-7a1b61fdd0be ] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 12:41:31.124 4436 INFO neutron.agent.dhcp_agent [-] DHCP agent started
2015-10-20 12:42:31.122 4436 ERROR neutron.agent.dhcp_agent [req-3c1c9ec1-9e07-4287-ac23-7a1b61fdd0be None] Failed reporting state!
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent Traceback (most recent call last):
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/neutron/agent/dhcp_agent.py", line 595, in _report_state
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     self.state_rpc.report_state(ctx, self.agent_state, self.use_call)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/neutron/agent/rpc.py", line 72, in report_state
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     return self.call(context, msg)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/neutron/common/log.py", line 34, in wrapper
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     return method(*args, **kwargs)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/neutron/common/rpc.py", line 161, in call
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     context, msg, rpc_method='call', **kwargs)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/neutron/common/rpc.py", line 187, in __call_rpc_method
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     return func(context, msg['method'], **msg['args'])
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/rpc/client.py", line 389, in call
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     return self.prepare().call(ctxt, method, **kwargs)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/rpc/client.py", line 152, in call
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     retry=self.retry)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/transport.py", line 90, in _send
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     timeout=timeout, retry=retry)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 416, in send
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     retry=retry)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 405, in _send
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     result = self._waiter.wait(msg_id, timeout)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 293, in wait
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     reply, ending = self._poll_connection(msg_id, timer)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 240, in _poll_connection
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     self._raise_timeout_exception(msg_id)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/amqpdriver.py", line 209, in _raise_timeout_exception
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent     _('Timed out waiting for a reply to message ID %s.') % msg_id)
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent MessagingTimeout: Timed out waiting for a reply to message ID 78a182793a8242fb9f8e17ec7bd9ca3f.
2015-10-20 12:42:31.122 4436 TRACE neutron.agent.dhcp_agent 
2015-10-20 12:42:31.146 4436 WARNING neutron.openstack.common.loopingcall [-] task run outlasted interval by 30.755455 sec
2015-10-20 12:42:31.334 4436 INFO neutron.agent.dhcp_agent [req-9820014f-23b0-43cf-acd0-5384beec0cb7 None] Synchronizing state
2015-10-20 12:42:31.851 4436 INFO neutron.agent.dhcp_agent [req-9820014f-23b0-43cf-acd0-5384beec0cb7 None] Synchronizing state complete
