2015-10-20 09:03:07.631 27971 AUDIT nova.service [-] Starting scheduler node (version 2014.2.3-31.el7ost)
2015-10-20 09:03:11.891 27971 INFO oslo.messaging._drivers.impl_rabbit [req-cb73406d-94c9-4f43-8e34-ae8ba93fc8ee ] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 09:03:11.970 27971 INFO oslo.messaging._drivers.impl_rabbit [req-cb73406d-94c9-4f43-8e34-ae8ba93fc8ee ] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 09:10:57.179 27971 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to consume message from queue: (0, 0): (320) CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 674, in ensure
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 762, in _consume
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit     return self.connection.drain_events(timeout=poll_timeout)
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit     return self.transport.drain_events(self.connection, **kwargs)
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 91, in drain_events
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit     return connection.drain_events(**kwargs)
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 323, in drain_events
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit     return amqp_method(channel, args)
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 529, in _close
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit     (class_id, method_id), ConnectionError)
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit ConnectionForced: (0, 0): (320) CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
2015-10-20 09:10:57.179 27971 TRACE oslo.messaging._drivers.impl_rabbit 
2015-10-20 09:10:57.191 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2015-10-20 09:10:58.194 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 09:10:58.330 27971 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 10.12.27.29:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 1 seconds.
2015-10-20 09:10:59.333 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2015-10-20 09:11:00.334 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 09:11:00.398 27971 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 10.12.27.29:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 3 seconds.
2015-10-20 09:11:03.400 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2015-10-20 09:11:04.406 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 09:11:04.847 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 10:17:23.158 27971 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to consume message from queue: [Errno 110] Connection timed out
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 674, in ensure
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 762, in _consume
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit     return self.connection.drain_events(timeout=poll_timeout)
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit     return self.transport.drain_events(self.connection, **kwargs)
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 91, in drain_events
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit     return connection.drain_events(**kwargs)
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 302, in drain_events
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit     chanmap, None, timeout=timeout,
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 365, in _wait_multiple
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit     channel, method_sig, args, content = read_timeout(timeout)
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 336, in read_timeout
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit     return self.method_reader.read_method()
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit     raise m
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit error: [Errno 110] Connection timed out
2015-10-20 10:17:23.158 27971 TRACE oslo.messaging._drivers.impl_rabbit 
2015-10-20 10:17:23.162 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2015-10-20 10:17:23.212 27971 WARNING nova.openstack.common.loopingcall [-] task <bound method DbDriver._report_state of <nova.servicegroup.drivers.db.DbDriver object at 0x30ddb90>> run outlasted interval by 15.93 sec
2015-10-20 10:17:24.165 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 10:17:24.282 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 10:54:19.179 27971 INFO oslo.messaging._drivers.impl_rabbit [req-05632eb8-480d-4988-86ec-066cfdd0d802 ] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 10:54:19.230 27971 INFO oslo.messaging._drivers.impl_rabbit [req-05632eb8-480d-4988-86ec-066cfdd0d802 ] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 12:20:25.642 27971 ERROR oslo.messaging._drivers.impl_rabbit [-] Failed to consume message from queue: (0, 0): (320) CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit Traceback (most recent call last):
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 674, in ensure
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit     return method()
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/oslo/messaging/_drivers/impl_rabbit.py", line 762, in _consume
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit     return self.connection.drain_events(timeout=poll_timeout)
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit     return self.transport.drain_events(self.connection, **kwargs)
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 91, in drain_events
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit     return connection.drain_events(**kwargs)
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 323, in drain_events
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit     return amqp_method(channel, args)
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit   File "/usr/lib/python2.7/site-packages/amqp/connection.py", line 529, in _close
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit     (class_id, method_id), ConnectionError)
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit ConnectionForced: (0, 0): (320) CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
2015-10-20 12:20:25.642 27971 TRACE oslo.messaging._drivers.impl_rabbit 
2015-10-20 12:20:25.646 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2015-10-20 12:20:26.648 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 12:20:26.719 27971 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 10.12.27.29:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 1 seconds.
2015-10-20 12:20:27.721 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Delaying reconnect for 1.0 seconds...
2015-10-20 12:20:28.723 27971 INFO oslo.messaging._drivers.impl_rabbit [-] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 12:20:28.776 27971 ERROR oslo.messaging._drivers.impl_rabbit [-] AMQP server on 10.12.27.29:5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 3 seconds.
2015-10-20 12:20:29.647 27971 INFO nova.openstack.common.service [-] Caught SIGTERM, exiting
2015-10-20 12:41:00.634 1420 AUDIT nova.service [-] Starting scheduler node (version 2014.2.3-31.el7ost)
2015-10-20 12:41:15.453 1420 WARNING oslo.db.sqlalchemy.session [req-e320f72b-3c64-4817-a3af-761ff85baf91 ] SQL connection failed. -1 attempts left.
2015-10-20 12:41:25.483 1420 WARNING oslo.db.sqlalchemy.session [req-e320f72b-3c64-4817-a3af-761ff85baf91 ] SQL connection failed. -2 attempts left.
2015-10-20 12:41:39.252 1420 INFO oslo.messaging._drivers.impl_rabbit [req-e320f72b-3c64-4817-a3af-761ff85baf91 ] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 12:41:39.368 1420 INFO oslo.messaging._drivers.impl_rabbit [req-e320f72b-3c64-4817-a3af-761ff85baf91 ] Connected to AMQP server on 10.12.27.29:5672
2015-10-20 13:42:12.373 1420 INFO oslo.messaging._drivers.impl_rabbit [req-01e605db-df9a-4a31-99d5-044a6f38375c ] Connecting to AMQP server on 10.12.27.29:5672
2015-10-20 13:42:12.428 1420 INFO oslo.messaging._drivers.impl_rabbit [req-01e605db-df9a-4a31-99d5-044a6f38375c ] Connected to AMQP server on 10.12.27.29:5672
